### ISSUE TITLE
Regex support?

### ISSUE THREAD

**Issue by denilsonsa** [ujihisa/unite-locate#5]
On Linux, we can use `locate -r regex`.

Can you please implement a way to use regular expressions in `unite-locate`? Maybe by detecting the `-r` prefix in the pattern typed by the user.

(By the way, how hard would it be to make `unite-locate` use vimproc? So that it can run `locate` in background without ever blocking the main Vim window.)

**Comment by ujihisa** [comment]
`-r` is possible to be implemented in the unite-locate itself, but it's already available for users just by temporary modifying `g:unite_locate_command`, so I feel like that's already fine as is.

unite-locate is already using vimproc, but yes I get what you mean; unite-locate could have used other ways besides `unite_source.gather_candidates` to paginate the results to minimize Vim to block. That sounds attractive for me ;)

**Comment by denilsonsa** [comment]
The idea of an on-the-fly regex switch is to let the user use regex only when needed, but not all the time. But, indeed, providing a custom command might be enough.

By the way, you should update [the documentation](https://github.com/ujihisa/unite-locate/blob/master/doc/unite-locate.txt), it still mentions `%d` and `%s`, while it should be `{count}` and `{query}`. ;)

**Comment by ujihisa** [comment]
Good catch! I'll fix the doc later.

**Comment by ujihisa** [comment]
> unite-locate is already using vimproc, but yes I get what you mean; unite-locate could have used other ways besides `unite_source.gather_candidates` to paginate the results to minimize Vim to block. That sounds attractive for me ;)

I found that current unite-locate implementation uses locate command with `-l` to specify count to cap the number of result, which should be enough; no need for pagination. I guess first think to work on is to do a performance benchmarking to detect where is the bottleneck.
